approvedGitRepositories:
  - "https://github.com/yarnpkg/*"
  - "ssh://git@github.com/yarnpkg/*"
  - "https://github.com/dimaslanjaka/*"

enableScripts: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.14.1.cjs
